# Scheme name: Summerfruit Light
# Scheme author: Christopher Corley (http://christop.club/)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Summerfruit Light
ColorForeground=#101010
ColorBackground=#FFFFFF
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#FFFFFF;#FF0086;#00C918;#ABA800;#3777E6;#AD00A1;#1FAAAA;#101010;#B0B0B0;#FF0086;#00C918;#ABA800;#3777E6;#AD00A1;#1FAAAA;#202020
