# Scheme name: Horizon Light
# Scheme author: Michaël Ball (http://github.com/michael-ball/)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Horizon Light
ColorForeground=#403C3D
ColorBackground=#FDF0ED
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#FDF0ED;#F7939B;#94E1B0;#FBE0D9;#DA103F;#1D8991;#DC3318;#403C3D;#BDB3B1;#F7939B;#94E1B0;#FBE0D9;#DA103F;#1D8991;#DC3318;#201C1D
