# Scheme name: OceanicNext
# Scheme author: https://github.com/voronianski/oceanic-next-color-scheme
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-OceanicNext
ColorForeground=#C0C5CE
ColorBackground=#1B2B34
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1B2B34;#EC5f67;#99C794;#FAC863;#6699CC;#C594C5;#5FB3B3;#C0C5CE;#65737E;#EC5f67;#99C794;#FAC863;#6699CC;#C594C5;#5FB3B3;#D8DEE9
