# Scheme name: Atelier Heath Light
# Scheme author: Bram de Haan (http://atelierbramdehaan.nl)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=-atelier-heath-light
ColorForeground=#695d69
ColorBackground=#f7f3f7
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#f7f3f7;#ca402b;#918b3b;#bb8a35;#516aec;#7b59c0;#159393;#695d69;#ab9bab;#;#;#;#;#;#;#1b181b
