# Scheme name: DanQing Light
# Scheme author: Wenhan Zhu (Cosmos) (zhuwenhan950913@gmail.com)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-DanQing Light
ColorForeground=#5a605d
ColorBackground=#fcfefd
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#fcfefd;#F9906F;#8AB361;#F0C239;#B0A4E3;#CCA4E3;#30DFF3;#5a605d;#cad8d2;#F9906F;#8AB361;#F0C239;#B0A4E3;#CCA4E3;#30DFF3;#2d302f
