# Scheme name: Google Dark
# Scheme author: Seth Wright (http://sethawright.com)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Google Dark.16
ColorForeground=#c5c8c6
ColorBackground=#1d1f21
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#282a2e;#CC342B;#198844;#FBA922;#3971ED;#3971ED;#3971ED;#e0e0e0;#1d1f21;#F96A38;#373b41;#969896;#b4b7b4;#A36AC7;#c5c8c6;#ffffff
