# Scheme name: Brush Trees Dark
# Scheme author: Abraham White &lt;abelincoln.white@gmail.com&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=-brushtrees-dark
ColorForeground=#B0C5C8
ColorBackground=#485867
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#485867;#b38686;#87b386;#aab386;#868cb3;#b386b2;#86b3b3;#B0C5C8;#6D828E;#;#;#;#;#;#;#E3EFEF
