# Scheme name: Summerfruit Light
# Scheme author: Christopher Corley (http://christop.club/)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=-summerfruit-light
ColorForeground=#101010
ColorBackground=#FFFFFF
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#FFFFFF;#FF0086;#00C918;#ABA800;#3777E6;#AD00A1;#1FAAAA;#101010;#D0D0D0;#;#;#;#;#;#;#202020
