# Scheme name: Horizon Dark
# Scheme author: Michaël Ball (http://github.com/michael-ball/)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=-horizon-dark
ColorForeground=#CBCED0
ColorBackground=#1C1E26
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1C1E26;#E93C58;#EFAF8E;#EFB993;#DF5273;#B072D1;#24A8B4;#CBCED0;#2E303E;#;#;#;#;#;#;#E3E6EE
