# Scheme name: Pasque
# Scheme author: Gabriel Fontes (https://github.com/Misterio77)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Pasque.16
ColorForeground=#DEDCDF
ColorBackground=#271C3A
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#100323;#A92258;#C6914B;#804ead;#8E7DC6;#59325C;#7263AA;#EDEAEF;#271C3A;#918889;#3E2D5C;#5D5766;#BEBCBF;#953B9D;#DEDCDF;#BBAADD
