# Scheme name: DanQing Light
# Scheme author: Wenhan Zhu (Cosmos) (zhuwenhan950913@gmail.com)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-DanQing Light.16
ColorForeground=#5a605d
ColorBackground=#fcfefd
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#ecf6f2;#F9906F;#8AB361;#F0C239;#B0A4E3;#CA6924;#30DFF3;#434846;#fcfefd;#B38A61;#e0f0eF;#cad8d2;#9da8a3;#CCA4E3;#5a605d;#2d302f
