# Scheme name: Horizon Light
# Scheme author: Michaël Ball (http://github.com/michael-ball/)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=-horizon-terminal-light
ColorForeground=#403C3D
ColorBackground=#FDF0ED
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#FDF0ED;#E95678;#29D398;#FADAD1;#26BBD9;#EE64AC;#59E1E3;#403C3D;#F9CBBE;#;#;#;#;#;#;#201C1D
