# Scheme name: OceanicNext
# Scheme author: https://github.com/voronianski/oceanic-next-color-scheme
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=-oceanicnext
ColorForeground=#C0C5CE
ColorBackground=#1B2B34
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1B2B34;#EC5f67;#99C794;#FAC863;#6699CC;#C594C5;#5FB3B3;#C0C5CE;#4F5B66;#;#;#;#;#;#;#D8DEE9
