# Scheme name: Brush Trees
# Scheme author: Abraham White &lt;abelincoln.white@gmail.com&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=-brushtrees
ColorForeground=#6D828E
ColorBackground=#E3EFEF
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#E3EFEF;#b38686;#87b386;#aab386;#868cb3;#b386b2;#86b3b3;#6D828E;#B0C5C8;#;#;#;#;#;#;#485867
