# Scheme name: DanQing
# Scheme author: Wenhan Zhu (Cosmos) (zhuwenhan950913@gmail.com)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-DanQing
ColorForeground=#e0f0eF
ColorBackground=#2d302f
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#2d302f;#F9906F;#8AB361;#F0C239;#B0A4E3;#CCA4E3;#30DFF3;#e0f0eF;#9da8a3;#F9906F;#8AB361;#F0C239;#B0A4E3;#CCA4E3;#30DFF3;#fcfefd
