# Scheme name: Dracula
# Scheme author: Mike Barkmin (http://github.com/mikebarkmin) based on Dracula Theme (http://github.com/dracula)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=-dracula
ColorForeground=#e9e9f4
ColorBackground=#282936
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#282936;#ea51b2;#ebff87;#00f769;#62d6e8;#b45bcf;#a1efe4;#e9e9f4;#4d4f68;#;#;#;#;#;#;#f7f7fb
