# Scheme name: Outrun Dark
# Scheme author: Hugo Delahousse (http://github.com/hugodelahousse/)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=-outrun-dark
ColorForeground=#D0D0FA
ColorBackground=#00002A
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#00002A;#FF4242;#59F176;#F3E877;#66B0FF;#F10596;#0EF0F0;#D0D0FA;#30305A;#;#;#;#;#;#;#F5F5FF
