# Scheme name: Silk Dark
# Scheme author: Gabriel Fontes (https://github.com/Misterio77)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Silk Dark
ColorForeground=#C7DBDD
ColorBackground=#0e3c46
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#0e3c46;#fb6953;#73d8ad;#fce380;#46bddd;#756b8a;#3fb2b9;#C7DBDD;#587073;#fb6953;#73d8ad;#fce380;#46bddd;#756b8a;#3fb2b9;#D2FAFF
