# Scheme name: Horizon Dark
# Scheme author: Michaël Ball (http://github.com/michael-ball/)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=-horizon-terminal-dark
ColorForeground=#CBCED0
ColorBackground=#1C1E26
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1C1E26;#E95678;#29D398;#FAC29A;#26BBD9;#EE64AC;#59E1E3;#CBCED0;#2E303E;#;#;#;#;#;#;#E3E6EE
